/*
 * Copyright ${year} Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package demo.large_project2;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Pojo35 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

   private java.math.BigDecimal field1;
   private java.math.BigDecimal field2;
   private java.math.BigDecimal field3;
   private java.math.BigDecimal field4;
   private java.math.BigDecimal field5;
   private java.math.BigDecimal field6;
   private java.math.BigDecimal field7;
   private java.math.BigDecimal field8;
   private java.math.BigDecimal field9;
   private java.math.BigDecimal field10;
   private java.math.BigDecimal field11;
   private java.math.BigDecimal field12;
   private java.math.BigDecimal field13;
   private java.math.BigDecimal field14;
   private java.math.BigDecimal field15;
   private java.math.BigDecimal field16;
   private java.math.BigDecimal field17;
   private java.math.BigDecimal field18;
   private java.math.BigDecimal field19;
   private java.math.BigDecimal field20;


   public java.math.BigDecimal getField1()
   {
      return this.field1;
   }

   public void setField1(java.math.BigDecimal field1)
   {
      this.field1 = field1;
   }

   public java.math.BigDecimal getField2()
   {
      return this.field2;
   }

   public void setField2(java.math.BigDecimal field2)
   {
      this.field2 = field2;
   }

   public java.math.BigDecimal getField3()
   {
      return this.field3;
   }

   public void setField3(java.math.BigDecimal field3)
   {
      this.field3 = field3;
   }

   public java.math.BigDecimal getField4()
   {
      return this.field4;
   }

   public void setField4(java.math.BigDecimal field4)
   {
      this.field4 = field4;
   }

   public java.math.BigDecimal getField5()
   {
      return this.field5;
   }

   public void setField5(java.math.BigDecimal field5)
   {
      this.field5 = field5;
   }

   public java.math.BigDecimal getField6()
   {
      return this.field6;
   }

   public void setField6(java.math.BigDecimal field6)
   {
      this.field6 = field6;
   }

   public java.math.BigDecimal getField7()
   {
      return this.field7;
   }

   public void setField7(java.math.BigDecimal field7)
   {
      this.field7 = field7;
   }

   public java.math.BigDecimal getField8()
   {
      return this.field8;
   }

   public void setField8(java.math.BigDecimal field8)
   {
      this.field8 = field8;
   }

   public java.math.BigDecimal getField9()
   {
      return this.field9;
   }

   public void setField9(java.math.BigDecimal field9)
   {
      this.field9 = field9;
   }

   public java.math.BigDecimal getField10()
   {
      return this.field10;
   }

   public void setField10(java.math.BigDecimal field10)
   {
      this.field10 = field10;
   }

   public java.math.BigDecimal getField11()
   {
      return this.field11;
   }

   public void setField11(java.math.BigDecimal field11)
   {
      this.field11 = field11;
   }

   public java.math.BigDecimal getField12()
   {
      return this.field12;
   }

   public void setField12(java.math.BigDecimal field12)
   {
      this.field12 = field12;
   }

   public java.math.BigDecimal getField13()
   {
      return this.field13;
   }

   public void setField13(java.math.BigDecimal field13)
   {
      this.field13 = field13;
   }

   public java.math.BigDecimal getField14()
   {
      return this.field14;
   }

   public void setField14(java.math.BigDecimal field14)
   {
      this.field14 = field14;
   }

   public java.math.BigDecimal getField15()
   {
      return this.field15;
   }

   public void setField15(java.math.BigDecimal field15)
   {
      this.field15 = field15;
   }

   public java.math.BigDecimal getField16()
   {
      return this.field16;
   }

   public void setField16(java.math.BigDecimal field16)
   {
      this.field16 = field16;
   }

   public java.math.BigDecimal getField17()
   {
      return this.field17;
   }

   public void setField17(java.math.BigDecimal field17)
   {
      this.field17 = field17;
   }

   public java.math.BigDecimal getField18()
   {
      return this.field18;
   }

   public void setField18(java.math.BigDecimal field18)
   {
      this.field18 = field18;
   }

   public java.math.BigDecimal getField19()
   {
      return this.field19;
   }

   public void setField19(java.math.BigDecimal field19)
   {
      this.field19 = field19;
   }

   public java.math.BigDecimal getField20()
   {
      return this.field20;
   }

   public void setField20(java.math.BigDecimal field20)
   {
      this.field20 = field20;
   }


    public Pojo35() {
    }

}